protected/controllers/DetalleVentaController.php
<?php

class DetalleVentaController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionIndex() {
                $this->redirect(array('listar'));
	}

	public function actionListar() {
		$dataProvider = new CActiveDataProvider('DetalleVenta');
		$this->render('listar', array(
			'dataProvider' => $dataProvider,
		));
	}        
        
	public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'DetalleVenta'),
		));
	}

	public function actionCrear() {
		$model = new DetalleVenta;

		$this->performAjaxValidation($model, 'detalle-venta-form');

		if (isset($_POST['DetalleVenta'])) {
			$model->setAttributes($_POST['DetalleVenta']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'DetalleVenta');

		$this->performAjaxValidation($model, 'detalle-venta-form');

		if (isset($_POST['DetalleVenta'])) {
			$model->setAttributes($_POST['DetalleVenta']);
                        
			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'DetalleVenta')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionAdministrar() {
                $session = new CHttpSession;
                $session->open();
		$model = new DetalleVenta('search');
		$model->unsetAttributes();

		if (isset($_GET['DetalleVenta'])){
			$model->setAttributes($_GET['DetalleVenta']);
                }

                $session['DetalleVenta_model_search'] = $model;
                
		$this->render('administrar', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['DetalleVenta_model_search']))
               {
                $model = $session['DetalleVenta_model_search'];
                $model = DetalleVenta::model()->findAll($model->search()->criteria);
               }
               else
                 $model = DetalleVenta::model()->findAll();
             $this->toExcel($model, array('id', 'cantidad', 'precio', 'no_aplicable', 'venta', 'servicio', 'producto'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['DetalleVenta_model_search']))
               {
                $model = $session['DetalleVenta_model_search'];
                $model = DetalleVenta::model()->findAll($model->search()->criteria);
               }
               else
                 $model = DetalleVenta::model()->findAll();
             $this->toExcel($model, array('id', 'cantidad', 'precio', 'no_aplicable', 'venta', 'servicio', 'producto'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}

//-------------------------------------------------------------------------------------------------------------        
        
	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'DetalleVenta'),
		));
	}

	public function actionCreate() {
		$model = new DetalleVenta;

		$this->performAjaxValidation($model, 'detalle-venta-form');

		if (isset($_POST['DetalleVenta'])) {
			$model->setAttributes($_POST['DetalleVenta']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'DetalleVenta');

		$this->performAjaxValidation($model, 'detalle-venta-form');

		if (isset($_POST['DetalleVenta'])) {
			$model->setAttributes($_POST['DetalleVenta']);
                        
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'DetalleVenta')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

        //Index
	public function actionList() {
		$dataProvider = new CActiveDataProvider('DetalleVenta');
                //$this->render('index', array(
		$this->render('list', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new DetalleVenta('search');
		$model->unsetAttributes();

		if (isset($_GET['DetalleVenta'])){
			$model->setAttributes($_GET['DetalleVenta']);
                }

                $session['DetalleVenta_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
}

protected/controllers/VentaController.php
<?php

class VentaController extends GxController {

        public function filters() {
                return array('rights');
        }
        public function actionAsignarestilista($id){
            $model = $this->loadModel($id, 'Venta');
            $model_servicio=null;
            
            
            foreach ($model->detalleVentas(array('scopes'=>array('servicios_no_asignados'))) as $detalle_venta) {
                if(isset($detalle_venta))
                    $model_servicio=$detalle_venta->servicio;
                if(isset($_POST['Servicio']) AND isset($model_servicio)){
                    if($_POST['Servicio']['id']!=$model_servicio->id){
                        break;
                    }
                }else{
                    break;
                }
                
            }
            if(isset($_POST['Servicio'])){
                $model_servicio_actualizado= $this->loadModel($_POST['Servicio']['id'], 'Servicio');
                $model_servicio_actualizado->scenario="asignacion";
                $model_servicio_actualizado->estilista_id=($_POST['Servicio']['estilista_id']);
                $model_servicio_actualizado->formula_id=($_POST['Servicio']['formula_id']);
                $model_servicio_actualizado->estado="FINALIZADO";
                
                if($model_servicio_actualizado->save(true)){
                    $model_servicio_actualizado->actualizarStock();
                    Yii::app()->getUser()->setFlash('success','<i class="icon-ok-sign"></i> Estilista asignado exitósamente!');
                }else
                    Yii::app()->getUser()->setFlash('error','Ocurrio un error, intente de nuevo');
                
                if(Yii::app()->request->isAjaxRequest){
                    if($model->verificarServicios()){ 
                        echo CJSON::encode(array('status'=>'success','estado'=>'terminado','mensaje'=>'ASIGNACION DE ESTILISTAS COMPLETADO EXITOSAMENTE','div_venta'=>$this->renderPartial('_venta', array('model' => $model,),true), 'div_detalle'=>$this->renderPartial('_detalles_venta', array('model' => $model),true)));
                        exit;
                    }
                                  
                }
                                       
            }            
            if (Yii::app()->request->isAjaxRequest)
                {
                    if(isset($model_servicio)){
                    echo CJSON::encode(array('status'=>'failure','estado'=>'asignacion simple', 'div'=>$this->renderPartial('asignar_estilista/_formulario', array('model' => $model_servicio,),true)));
                    exit;
                    }else{
                        echo CJSON::encode(array('status'=>'failure','estado'=>'sin servicios', 'div'=>'NO POSEE SERVICIOS PENDIENTES'));
                        exit;
                    }
                }
            
            
            
        }
        public function actionPagarVenta($id){                
            $model = $this->loadModel($id, 'Venta');
            $model->tipo_pago="Efectivo";
            $model->cantidad_pago=$model->total;
            $model->cantidad_vuelto=0;
            
            if(!$model->verificarServicios()){
                if (Yii::app()->request->isAjaxRequest)
                {
                    echo CJSON::encode(array('status'=>'failure', 'div'=>'RECUERDE, UD. DEBE ASIGNAR UN ESTILISTA A LOS SERVICIOS'));
                    exit;               
                }
            }
            if (isset($_POST['Venta'])){
                $model->tipo_pago=($_POST['Venta']['tipo_pago']);
                $model->cantidad_pago=($_POST['Venta']['cantidad_pago']);
                $model->estado="PAGADA";
                $model->actualizarStock('pagar');
                $model->save();
                if(Yii::app()->request->isAjaxRequest){
                    echo CJSON::encode(array('status'=>'success','mensaje'=>'PAGO INGRESADO EXITOSAMENTE', 'div'=>$this->renderPartial('_venta', array('model' => $model,),true)));
                    exit;               
                }                       
            }               
            if (Yii::app()->request->isAjaxRequest)
                {
                    echo CJSON::encode(array('status'=>'failure', 'div'=>$this->renderPartial('_pagar', array('model' => $model,),true)));
                    exit;               
                }
        }
        
	public function actionIndex() {
                $this->render('listar', array());
	}

	public function actionListar() {
            $this->redirect(array('listar'));	
	}        
        
	public function actionAnular($id) {
                $model=$this->loadModel($id, 'Venta');
                $model->estado = "ANULADA";
                $model->actualizarStock('anular');
                $model->validate();
                $model->save();
                $this->redirect(array('ver', 'id' =>$model->id));
	}
        public function actionVer($id) {
                $model=$this->loadModel($id, 'Venta');
                if($model->estado!="NUEVA")
                Yii::app()->getUser()->setFlash('info','<i class="icon-info-sign"></i> Esta venta se encuentra <strong>'.$model->estado.'</strong> ');
		$this->render('ver', array(
			'model' => $model,
		));
	}
        public function actionProcesarProducto(){
            $model_producto=false;
            $model_detalle_producto=null;
            if(isset($_POST['codigo_barra'])){
                $model_detalle_producto = DetalleProducto::model()->findByAttributes(array('estado'=>'NUEVO', 'codigo_barra'=>$_POST['codigo_barra']));
                if(isset($model_detalle_producto)){
                    $model_detalle_producto->estado="PROCESO";
                    $model_detalle_producto->fecha_modificacion=date("Y-m-d H:i:s");
                    $model_detalle_producto->save();
                    Yii::app()->getUser()->setFlash('info','<i class="icon-info-sign"></i> Producto <strong>PROCESADO</strong> exitosamente');
                    $model_producto=true;
                }else{
                    Yii::app()->getUser()->setFlash('error','<i class="icon-info-sign"></i> Producto <strong>NO</strong> encontrado, intente de nuevo');
                }
            }
            $this->render('procesar_producto', array('model_producto'=>$model_producto,'model_detalle_producto'=>$model_detalle_producto));
        }
        
        public function actionGetTotalventa($id){
            $model= $this->loadModel($id, 'Venta');
            echo "$".Yii::app()->format->formatNumber($model->calcularTotal());            
        }
        
        public function actionCrearDetalleVenta($id) {
                $model_detalle_venta = new DetalleVenta;
                $model_venta = $this->loadModel($id,'Venta');
                $model_detalle_venta->venta_id = $model_venta->id;
                $model_producto= new Producto;
                
                if($model_venta->estado=="ANULADA")
                    $this->redirect(array('ver', 'id' => $model_venta->id));  
                                
                if(isset($_POST['no_aplicable'])){
                    $model_detalle_venta->no_aplicable=1;
                }
                if(isset($_POST['agregar'])){
                    if(isset($_POST['codigo_barra'])){
                        $model_tipo_servicio = TipoServicio::model()->findByAttributes(array('codigo_barra'=>$_POST['codigo_barra']));
                        if(isset($model_tipo_servicio)){
                            
                            $model_servicio = new Servicio();
                            $model_servicio->fecha = date("Y-m-d H:i:s");
                            $model_servicio->tipo_servicio_id=$model_tipo_servicio->id;
                            $model_servicio->cliente_id=$model_venta->cliente_id;
                            if($model_detalle_venta->no_aplicable)
                                $model_servicio->estado="N/A";
                            $model_servicio->validate();
                            $model_servicio->save(false);
                            
                            $model_detalle_venta->servicio_id=$model_servicio->id;
                            $model_detalle_venta->precio=$model_tipo_servicio->precio_venta;
                            $model_detalle_venta->validate();
                            $model_detalle_venta->save(false);

                            Yii::app()->getUser()->setFlash('info','<i class="icon-info-sign"></i> Recuerde que debe asignar un estilista al servicio '.$model_tipo_servicio->nombre);
                        }else{
                          $model_producto = Producto::model()->findByAttributes(array('tipo'=>'TERMINADO', 'codigo_barra'=>$_POST['codigo_barra']));
                          if(isset($model_producto)){
                            $model_detalle_venta->producto_id =  $model_producto->id;
                            $model_detalle_venta->precio = $model_producto->precio_venta;
                            if($model_detalle_venta->validate())
                                $model_detalle_venta->save(true);
                            Yii::app()->getUser()->setFlash('success','<i class="icon-ok-sign"></i> Producto agregado exitósamente!');
                        }else{
                            Yii::app()->getUser()->setFlash('error','Debe ingresar un producto disponible en el inventario.');
                        }  
                        }                        
                        
                    }
                }elseif(isset($_POST['terminar'])){                    
                        $model_venta->total=$model_venta->calcularTotal();
                        $model_venta->validate();
                        $model_venta->save(false);
                        $this->redirect(array('ver', 'id' => $model_venta->id));                    
                }
            

protected/views/detalleVenta/_busqueda.php
<div class="wide form">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'search-detalle-venta-form',
	'action'=>Yii::app()->createUrl($this->route),
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
	'method'=>'get',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<?php echo $form->textFieldControlGroup($model,'id', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->textFieldControlGroup($model,'cantidad', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->textFieldControlGroup($model,'precio', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->textFieldControlGroup($model,'no_aplicable', array('span'=>3, 'maxlength'=>4)); ?>

	<?php echo $form->dropDownListControlGroup($model,'venta_id', GxHtml::listDataEx(Venta::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'All') ));?>

	<?php echo $form->dropDownListControlGroup($model,'servicio_id', GxHtml::listDataEx(Servicio::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'All') ));?>

	<?php echo $form->dropDownListControlGroup($model,'producto_id', GxHtml::listDataEx(Producto::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'All') ));?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton(Yii::t('app', 'Search'),  array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'icon'=>'white search'));?>
        <?php echo TbHtml::resetButton(Yii::t('app', 'Reset'), array('icon'=>'icon-remove-sign')); ?>
        </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>


protected/views/detalleVenta/_form.php

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'detalle-venta-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<?php echo $form->textFieldControlGroup($model,'cantidad', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'precio', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'no_aplicable', array('span'=>3, 'maxlength'=>4)); ?>
		<?php echo $form->dropDownListControlGroup($model,'venta_id', GxHtml::listDataEx(Venta::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>
		<?php echo $form->dropDownListControlGroup($model,'servicio_id', GxHtml::listDataEx(Servicio::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>
		<?php echo $form->dropDownListControlGroup($model,'producto_id', GxHtml::listDataEx(Producto::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>
   
        
<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>

protected/views/detalleVenta/_formulario.php

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'detalle-venta-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<?php echo $form->textFieldControlGroup($model,'cantidad', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'precio', array('span'=>3, 'maxlength'=>11)); ?>
		<?php #echo $form->textFieldControlGroup($model,'no_aplicable', array('span'=>3, 'maxlength'=>4)); ?>
        <div class="control-group">
                        <?php echo $form->labelEx($model,'no_aplicable', array('class'=>'control-label')); ?>
                        <div clas="controls">
                                <?php echo $form->checkBox($model,'no_aplicable', array('class'=>'statuspicker')); ?>
                        </div>
                        <?php echo $form->error($model,'no_aplicable'); ?>
                </div>
        
		<?php echo $form->dropDownListControlGroup($model,'venta_id', GxHtml::listDataEx(Venta::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>
		<?php echo $form->dropDownListControlGroup($model,'servicio_id', GxHtml::listDataEx(Servicio::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>
		<?php echo $form->dropDownListControlGroup($model,'producto_id', GxHtml::listDataEx(Producto::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>

<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
        <?php $this->widget('ext.switch.TbSwitch'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>

protected/views/detalleVenta/ver.php
<?php

$this->breadcrumbs = array(

);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('actualizar', 'id' => $model->id), 'icon'=>'pencil'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('borrar', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
		'id',
		'cantidad',
		'precio',
		'no_aplicable',
		array(
			'name' => 'venta',
			'type' => 'raw',
			'value' => $model->venta !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->venta)), array('venta/ver', 'id' => GxActiveRecord::extractPkValue($model->venta, true))) : null,
			),
		array(
			'name' => 'servicio',
			'type' => 'raw',
			'value' => $model->servicio !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->servicio)), array('servicio/ver', 'id' => GxActiveRecord::extractPkValue($model->servicio, true))) : null,
			),
		array(
			'name' => 'producto',
			'type' => 'raw',
			'value' => $model->producto !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->producto)), array('producto/ver', 'id' => GxActiveRecord::extractPkValue($model->producto, true))) : null,
			),
	),
)); ?>

protected/views/detalleVenta/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('list'),
	GxHtml::valueEx($model),
);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('list'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create'), 'url'=>array('create'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id), 'icon'=>'pencil'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), TbHtml::labelTb('Admin')); ?>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
		'id',
		'cantidad',
		'precio',
		'no_aplicable',
		array(
			'name' => 'venta',
			'type' => 'raw',
			'value' => $model->venta !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->venta)), array('venta/view', 'id' => GxActiveRecord::extractPkValue($model->venta, true))) : null,
			),
		array(
			'name' => 'servicio',
			'type' => 'raw',
			'value' => $model->servicio !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->servicio)), array('servicio/view', 'id' => GxActiveRecord::extractPkValue($model->servicio, true))) : null,
			),
		array(
			'name' => 'producto',
			'type' => 'raw',
			'value' => $model->producto !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->producto)), array('producto/view', 'id' => GxActiveRecord::extractPkValue($model->producto, true))) : null,
			),
	),
)); ?>
